global:
  resolve_timeout: 5m

route:
  receiver: 'dispatcher'

receivers:
  - name: 'dispatcher'
    webhook_configs:
      - url: 'http://dispatcher:5000/alert'  
        send_resolved: true
        http_config:
          bearer_token: ''