version: '3.7'

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml

    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager:latest
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - ./message.tmpl:/etc/alertmanager/message.tmpl
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    volumes:
      - ./grafana-provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"

  dispatcher:
    container_name: dispatcher
    build:
      context: ./ 
    ports:
      - "5000:5000"